version: '3.8' # up-to-date

services: 
  db:
    image: postgres
    container_name: postgres-db-2024
    restart: always
    environment: 
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    volumes:
      - pgdata-2024:/var/lib/postgresql/data
    networks:
      - my_network
    ports: 
      - "${POSTGRES_PORT}:5432"

  nestjs:
    image: nestjs-rest-service-2024
    container_name: nest-rest-service-2024
    build: 
      context: .
      dockerfile: ./Dockerfile
    restart: always
    env_file:
      - .env
    ports: 
      - "${PORT}:${PORT}" # expose-to-the-world : only-in-the-docker
    depends_on: 
      - db
    networks:
      - my_network
    volumes: 
      - .:/app
      - node_modules-2024:/app/node_modules

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4-2024
    restart: always
    environment: 
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    ports: 
      - "8080:80"
    volumes: 
      - pgadmin-data-2024:/var/lib/pgadmin
    depends_on: 
      - db
    networks:
      - my_network

volumes:
  pgdata-2024:
  pgadmin-data-2024:
  node_modules-2024:

networks:
  my_network:
    driver: bridge